# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: rdfriedl/circleci-node-aws

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependancies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run:
          name: gatsby build
          command: npm run build

      - run:
          name: Clean s3 bucket
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              aws s3 rm s3://${BUCKER_NAME}/ --recursive;
            fi

      - deploy:
          name: Deploy to s3 bucket
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              aws s3 sync public s3://${BUCKET_NAME}/ --acl public-read;
            fi
