# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: rdfriedl/circleci-node-aws

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install dependancies
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: gatsby build
          command: yarn run build

      - deploy:
          name: Deploy to s3 bucket
          command: |
            if [ "${CIRCLE_BRANCH}" == "${DEPLOY_BRANCH}" ]; then
              aws configure set preview.cloudfront true && \
              echo delopying to bucket ${S3_BUCKET} && \
              aws s3 rm s3://${BUCKER_NAME} --recursive && \
              aws s3 sync public s3://${S3_BUCKET} --acl public-read && \
              aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths /*;
            fi